accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.SignupView.as_view(), name='signup'),
    #path('home/', views.HomeView.as_view(), name='home'),
    path('verify/', views.VerifyTokenView.as_view(), name='verify'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.Profile, name='profile'),
    path('updateprofile/', views.ProfileUpdateView, name='updateprofile'),
    path('add_info/', views.Account_info.as_view(), name='info'),
    path('add_info2/', views.Account_info2.as_view(), name='info2'),
    path('interests/', views.Account_interests.as_view(), name='interests'),
    path('confirmlogout/', views.LogoutConfirmView, name='logoutconfirm'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views
from .views import (LikeView, TweetDeleteView, TweetListView,
                    TweetUpdateView, create_post)

app_name = "posts"

urlpatterns = [
    path('home/', TweetListView.as_view(), name='home'),
    path('create_tweet/', create_post, name='createtweet'),
    path('tweet/<int:pk>/update', TweetUpdateView.as_view(), name='tweetupdate'),
    path('tweet/<int:pk>/delete', TweetDeleteView.as_view(), name='tweetdelete'),
    path('like/<int:pk>', LikeView, name='like_tweet'),
]

twitterClone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('posts.urls')),
]
if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

posts/models.py
import os

from accounts.models import Interest, Profile, User
from django.db import models
from taggit.managers import TaggableManager


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='author')

    body = models.TextField()

    create_date = models.DateTimeField(auto_now_add=True)

    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=type)
    likes = models.ManyToManyField(User, related_name='tweets')
    topic = models.ManyToManyField(Interest, related_name='topic')

    # tags = TaggableManager()

    def __str__(self):
        return str(self.body)

    # @property
    # def get_liked(self):
    #     return self.liked.all()
    #
    @property
    def like_count(self):
        return self.likes.count()

    # def get_total_likes(self):
    #     return self.likes.users.count()


def file_path_dir(instance, filename):

    return "uploaded/user" + "/" + str(instance.post.author.profile.user_name) + "/post/" + str(instance.post) + "/" + filename


class Files(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=False)
    file = models.FileField(upload_to=file_path_dir, null=True, blank=True)

    def __str__(self):
        return self.post.body + 'File'

posts/forms.py
from django.forms import ClearableFileInput
from django import forms

from posts.models import Post, Files


class FeedModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['body']


class FileModelForm(forms.ModelForm):
    class Meta:
        model = Files
        fields = ['file']
        widgets = {
            'file': ClearableFileInput(attrs={'multiple': True}),
        }

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView
from .models import Post, Files
from .forms import FeedModelForm, FileModelForm


def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True

    return HttpResponseRedirect(reverse('posts:home'))


class TweetListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'home.html'
    ordering = ['-create_date']


def create_post(request):
    if request.method == 'POST':
        author = request.user
        post_form = FeedModelForm(request.POST)
        file_form = FileModelForm(request.POST, request.FILES)
        files = request.FILES.getlist('file')
        if post_form.is_valid() and file_form.is_valid():
            post_instance = post_form.save(commit=False)

            post_instance.author = author

            post_instance.save()
            file_instance = file_form.save(commit=False)
            #            file_instance.post = post_instance
            #          file_instance.save()

            for f in files:
                file_instance.post = Files(file=f, post=post_instance).save()

        return redirect('/home/')
    else:
        post_form = FeedModelForm()
        file_form = FileModelForm()
        return render(request, 'create.html', {'post_form': post_form, 'file_form': file_form})


'''class TweetCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'create.html'
    fields = ['media', 'body', 'topic']
    success_url = '/home'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)'''


class TweetUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'create.html'
    fields = ['body', 'topic']
    success_url = '/home'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class TweetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'tweet_confirm_delete.html'
    fields = ['body']
    success_url = '/home'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

posts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<style>
.avatar {
  vertical-align: middle;
  width: 50px;
  height: 50px;
  border-radius: 50%;
}
</style>



</head>
<body>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

   <br>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'posts:home' %}"><h6>Home</h6> </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:profile' %}"><h6>Profile</h6></a>
              </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:logoutconfirm' %}"><h6>Logout</h6></a>
              </li>



            </ul>
      </div>
  </nav>


{% block content %}

{% endblock content %}

</body>
</html>

posts/templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<style>
.avatar {
  vertical-align: middle;
  width: 50px;
  height: 50px;
  border-radius: 50%;
}
</style>



</head>
<body>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

   <br>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'posts:home' %}"><h6>Home</h6> </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:profile' %}"><h6>Profile</h6></a>
              </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:logoutconfirm' %}"><h6>Logout</h6></a>
              </li>



            </ul>
      </div>
  </nav>


{% block content %}

{% endblock content %}

</body>
</html>

posts/templates/create.html
{% extends 'base.html' %}

{%block content%}

<div class="container">
<br><br>
   <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
       <fieldset class="form-group">
         <legend class="border-bottom mb-4"> Write Here  </legend>
            <table>
                {{ post_form.as_table}}
                {{ file_form.as_table}}
            </table>
        </fieldset>

             <button type="submit" class="btn btn-primary">Tweet</button>
    </form>
</div>


{%endblock content%}

posts/templates/home.html
{% extends 'base.html' %}

{%block content%}

        <div class="jumbotron">
          <h1 class="display-4">Hello, {{user.profile.user_name}}!</h1>
          <p class="lead">This is a simple twitter clone ! </p>
          <hr class="my-4">
          <p>Click below to Create Tweet</p>
          <p class="lead">
            <a class="btn btn-primary btn-lg" href='{% url "posts:createtweet" %}' role="button">Create tweet</a>
          </p>
        </div>

    <br>

<div class="container-fluid" >
        {% for post in object_list %}
                    <br>
                  <div class="card w-50" >
                      <div class="card-header">
                       <a  class="nav-link" href="#"><h5>{{post.author.profile.user_name}}</h5></a>
                      </div>
                  <div class="card-body">
                      <h5 class="card-title"> </h5>
                      <p class="card-text"><h5>{{post.body}}</h5></p>
                       <p><h6>{{post.create_date}}</h6></p>
                           {% if post.author == user  %}
                          <a href='{% url "posts:tweetupdate" post.id %}'> <button  class="btn btn-outline-info" type="submit">Edit</button></a>
                          <a href='{% url "posts:tweetdelete" post.id %}'> <button  class="btn btn-outline-danger" type="submit">Delete</button></a>

                          {% endif %}
                          
                          <form action="{% url 'posts:like_tweet' post.id %}" method="POST">
                            {% csrf_token %}
                            {% if user in post.likes.all %}
                            <button class="btn btn-block btn-outline-danger" type="submit", name="post_id", value="{{ post.id }}"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                              <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"></path>
                            </svg> Liked </button>
                            {% else %}
                            <button class="btn btn-block btn-primary" type="submit", name="post_id", value="{{ post.id }}"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                              <path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"></path>
                            </svg> Like </button>
                            {% endif %}
                            Likes: {{ post.like_count }}
                            
                        </form>
                  </div>

                </div>
        {% endfor %}
    </div>


{%if messages %}
	<div class="alert alert-danger" role="alert">

	{% for message in messages %}
	<h5 align="center">{{message}}</h5>
	{% endfor %}

	</div>
	{%endif%}

{%endblock content%}

posts/templates/tweet_confirm_delete.html
{% extends 'base.html' %}

{%block content%}

<div class="container">
   <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
       <fieldset class="form-group">
         <legend class="border-bottom mb-4"> Confirm Delete!  </legend>
            <table>
                {{ form.as_table}}
            </table>
        </fieldset>

             <button class="btn btn-danger" type="submit">Delete</button>
    </form>
    <br>
    <a href='{%url "posts:home"%}'> <button  class="btn btn-outline-info" >Cancel</button></a>
</div>

{%endblock content%}